//! Compiled protobuf types for all gRPC services.
//!
//! Generated by prost-build in build.rs from `construct-server/shared/proto/`.
//! The module hierarchy mirrors the proto package declarations:
//!   `shared.proto.core.v1`      → `proto::core::v1`
//!   `shared.proto.messaging.v1` → `proto::messaging::v1`
//!   `shared.proto.services.v1`  → `proto::services::v1`
//!   `shared.proto.signaling.v1` → `proto::signaling::v1`

/// Core types: Envelope, Identity, Crypto, Pagination
pub mod core {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/shared.proto.core.v1.rs"));
    }
}

/// Messaging wire types: SignalMessage, PreKeySignalMessage, ContentMessage
pub mod messaging {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/shared.proto.messaging.v1.rs"));
    }
}

/// Service request/response types: Auth, Key, Messaging, User, Notification
pub mod services {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/shared.proto.services.v1.rs"));
    }
}

/// Signaling types: DeliveryReceipt, PresenceUpdate, WebRTC
pub mod signaling {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/shared.proto.signaling.v1.rs"));
    }
}
